global:
  scrape_interval: 5s  # 메트릭 수집 주기 (기본값은 1분 → 실시간 보려면 짧게)

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']